SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  type ENUM('hotspot','pppoe') NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  duration_hours INT DEFAULT NULL,
  data_cap_mb INT DEFAULT NULL,
  speed_down_kbps INT DEFAULT NULL,
  speed_up_kbps INT DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tenant (tenant_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS routers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  model VARCHAR(100) DEFAULT NULL,
  routeros_version VARCHAR(30) DEFAULT NULL,
  host VARCHAR(150) NOT NULL,
  port INT DEFAULT 8728,
  username VARCHAR(100) NOT NULL,
  password_encrypted VARCHAR(500) NOT NULL,
  api_type ENUM('api','api_ssl','rest') DEFAULT 'api',
  site_name VARCHAR(150) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  status ENUM('online','offline','unknown') DEFAULT 'unknown',
  last_seen DATETIME DEFAULT NULL,
  wireguard_enabled TINYINT(1) DEFAULT 0,
  wireguard_ip VARCHAR(45) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tenant (tenant_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subscribers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  account_number VARCHAR(50) NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  type ENUM('hotspot','pppoe','static') NOT NULL DEFAULT 'hotspot',
  plan_id INT DEFAULT NULL,
  router_id INT DEFAULT NULL,
  username VARCHAR(100) NOT NULL,
  password_plain VARCHAR(100) DEFAULT NULL,
  mac_address VARCHAR(20) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  status ENUM('active','expired','suspended','pending') DEFAULT 'pending',
  activated_at DATETIME DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  data_used_mb INT DEFAULT 0,
  time_used_sec INT DEFAULT 0,
  notes TEXT DEFAULT NULL,
  created_by INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tenant_account (tenant_id, account_number),
  UNIQUE KEY uniq_tenant_username (tenant_id, username),
  INDEX idx_tenant (tenant_id),
  INDEX idx_status (status),
  INDEX idx_expires (expires_at),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL,
  FOREIGN KEY (router_id) REFERENCES routers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
