SET NAMES utf8mb4;

-- Add branding columns to tenants
ALTER TABLE tenants
  ADD COLUMN tagline VARCHAR(200) DEFAULT NULL AFTER logo_url,
  ADD COLUMN favicon_url VARCHAR(500) DEFAULT NULL AFTER tagline,
  ADD COLUMN website VARCHAR(200) DEFAULT NULL AFTER contact_phone,
  ADD COLUMN address_line1 VARCHAR(200) DEFAULT NULL,
  ADD COLUMN address_line2 VARCHAR(200) DEFAULT NULL,
  ADD COLUMN city VARCHAR(100) DEFAULT NULL,
  ADD COLUMN country_code VARCHAR(5) DEFAULT 'KE',
  ADD COLUMN facebook_url VARCHAR(300) DEFAULT NULL,
  ADD COLUMN twitter_url VARCHAR(300) DEFAULT NULL,
  ADD COLUMN instagram_url VARCHAR(300) DEFAULT NULL,
  ADD COLUMN whatsapp_number VARCHAR(30) DEFAULT NULL,
  ADD COLUMN invoice_footer TEXT DEFAULT NULL;
